<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserPayments extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('user_payments')->insert([
            [
                "user_id" => 5,
                "session_id" => 1,
                "amount" => 40,
                "tax_amount" => 5.2,
                "total_amount" => 58.33,
                "adminFee" => 10,
                "adminFeeTax" => 11.3,
                "stripe_charges" => 1.83,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 1.46,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],
            [
                "user_id" => 5,
                "session_id" => 2,
                "amount" => 80,
                "tax_amount" => 10.04,
                "total_amount" => 116.67,
                "adminFee" => 20,
                "adminFeeTax" => 22.6,
                "stripe_charges" => 3.66,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 2.92,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],
            [
                "user_id" => 5,
                "session_id" => 3,
                "amount" => 40,
                "tax_amount" => 5.2,
                "total_amount" => 58.33,
                "adminFee" => 10,
                "adminFeeTax" => 11.3,
                "stripe_charges" => 1.83,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 1.46,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],
            [
                "user_id" => 5,
                "session_id" => 4,
                "amount" => 40,
                "tax_amount" => 5.2,
                "total_amount" => 58.33,
                "adminFee" => 10,
                "adminFeeTax" => 11.3,
                "stripe_charges" => 1.83,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 1.46,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],
            [
                "user_id" => 5,
                "session_id" => 5,
                "amount" => 40,
                "tax_amount" => 5.2,
                "total_amount" => 58.33,
                "adminFee" => 10,
                "adminFeeTax" => 11.3,
                "stripe_charges" => 1.83,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 1.46,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],

            [
                "user_id" => 6,
                "session_id" => 6,
                "amount" => 40,
                "tax_amount" => 5.2,
                "total_amount" => 58.33,
                "adminFee" => 10,
                "adminFeeTax" => 11.3,
                "stripe_charges" => 1.83,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 1.46,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],
            [
                "user_id" => 7,
                "session_id" => 7,
                "amount" => 80,
                "tax_amount" => 10.04,
                "total_amount" => 116.67,
                "adminFee" => 20,
                "adminFeeTax" => 22.6,
                "stripe_charges" => 3.66,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 2.92,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],
            [
                "user_id" => 8,
                "session_id" => 8,
                "amount" => 40,
                "tax_amount" => 5.2,
                "total_amount" => 58.33,
                "adminFee" => 10,
                "adminFeeTax" => 11.3,
                "stripe_charges" => 1.83,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 1.46,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],
            [
                "user_id" => 9,
                "session_id" => 9,
                "amount" => 40,
                "tax_amount" => 5.2,
                "total_amount" => 58.33,
                "adminFee" => 10,
                "adminFeeTax" => 11.3,
                "stripe_charges" => 1.83,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 1.46,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],
            [
                "user_id" => 10,
                "session_id" => 10,
                "amount" => 40,
                "tax_amount" => 5.2,
                "total_amount" => 58.33,
                "adminFee" => 10,
                "adminFeeTax" => 11.3,
                "stripe_charges" => 1.83,
                "user_type" => 'trainer',
                "stripe_payment_response" => null,
                "stripe_customer_id" => null,
                "charge_id" => null,
                "balance_transaction" => null,
                "pro_rate_billing" => 1.46,
                "receipt_url" => null,
                "status" => 'pending',
                "payment_status" => 'Unpaid',
            ],

        ]);
    }
}
